# Generated by Django 4.2.11 on 2024-04-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='likeanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.answer'),
        ),
    ]
