# Generated by Django 4.2.11 on 2024-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_likeanswer_question_likeanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/pic/aph.jpg', null=True, upload_to='static/pic'),
        ),
    ]
